# Generated by Django 4.1.5 on 2024-03-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=50, unique=True)),
                ('cliente_ceco', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('division_nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso_cliente', models.CharField(max_length=100)),
                ('ingreso_division', models.CharField(max_length=100)),
                ('ingreso_mes', models.CharField(max_length=10)),
                ('ingreso_anno', models.CharField(max_length=4)),
                ('ingreso_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_forecast', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_ceco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_ceco', to='data_financiera.cliente')),
                ('ingreso_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_pais', to='data_financiera.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Operacional',
            fields=[
                ('id_gas_op', models.AutoField(primary_key=True, serialize=False)),
                ('gas_op_ceco', models.CharField(max_length=15)),
                ('gas_op_mes', models.CharField(max_length=10)),
                ('gas_op_anno', models.CharField(max_length=4)),
                ('gas_op_real', models.CharField(max_length=5)),
                ('gas_op_forecast', models.CharField(max_length=5)),
                ('gas_op_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.cliente')),
                ('gas_op_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.division')),
                ('gas_op_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('costo_ceco', models.CharField(max_length=15)),
                ('costo_mes', models.CharField(max_length=10)),
                ('costo_anno', models.CharField(max_length=4)),
                ('costo_real', models.CharField(max_length=5)),
                ('costo_forecast', models.CharField(max_length=5)),
                ('costo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.cliente')),
                ('costo_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.division')),
                ('costo_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.pais')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_financiera.division'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_cliente', to='data_financiera.pais'),
        ),
    ]
