# Generated by Django 4.1.5 on 2024-03-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0002_tabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla',
        ),
    ]
