# Generated by Django 4.1.5 on 2024-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0003_delete_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_ceco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_pais',
            field=models.CharField(max_length=50),
        ),
    ]
