# Generated by Django 4.1.5 on 2024-03-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0004_alter_ingreso_ingreso_ceco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='costo_ceco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_division',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_forecast',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_real',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_ceco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_division',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_forecast',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_real',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
