# Generated by Django 4.1.5 on 2024-03-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0006_alter_cliente_cliente_ceco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_forecast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
