# Generated by Django 4.1.5 on 2024-03-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0007_alter_ingreso_ingreso_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_forecast',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ingreso_real',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
