# Generated by Django 4.1.5 on 2024-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_financiera', '0008_alter_ingreso_ingreso_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='costo_forecast',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='costo_real',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_forecast',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasto_operacional',
            name='gas_op_real',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
